// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Bitacora
{
    public int IdBitacora { get; set; }

    public int IdInforme { get; set; }

    public int IdMantenimiento { get; set; }

    public DateTime FechaHora { get; set; }

    public string Descripcion { get; set; }

    public string ImagenUrl { get; set; }

    public virtual Informes_Encabezado IdInformeNavigation { get; set; }

    public virtual Mantenimiento IdMantenimientoNavigation { get; set; }
}