// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Bitacora
{
    public int id_bitacora { get; set; }

    public int? id_cronogramas { get; set; }

    public DateTime? fecha_hora { get; set; }

    public string descripcion { get; set; }

    public string imagen_url { get; set; }

    public virtual Cronogramas id_cronogramasNavigation { get; set; }
}