// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Cronogramas
{
    public int id_cronogramas { get; set; }

    public int? id_usuario { get; set; }

    public int? id_parqueadero { get; set; }

    public int? id_mantenimiento { get; set; }

    public DateTime? fecha_inicio { get; set; }

    public DateTime? fecha_creacion { get; set; }

    public DateTime? fecha_fin { get; set; }

    public string observaciones { get; set; }

    public virtual ICollection<Bitacora> Bitacora { get; set; } = new List<Bitacora>();

    public virtual ICollection<Informes_Encabezado> Informes_Encabezado { get; set; } = new List<Informes_Encabezado>();

    public virtual Mantenimientos id_mantenimientoNavigation { get; set; }

    public virtual Parquadero id_parqueaderoNavigation { get; set; }

    public virtual Usuarios id_usuarioNavigation { get; set; }
}