// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Detalle_Informe
{
    public int IdDetInfo { get; set; }
    public int? IdInforme { get; set; }
    public string Descripcion { get; set; }
    public string ArchivoUrl { get; set; }
    public bool EstaEliminado { get; set; }
    public DateTime FechaCreacion { get; set; }
    public DateTime FechaModificacion { get; set; }

    public virtual Informes_Encabezado IdInformeNavigation { get; set; }
}