// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Detalle_Informe
{
    public int id_detInfo { get; set; }

    public int id_informe { get; set; }

    public string descripcion { get; set; }

    public string archivo_url { get; set; }

    public virtual Informes_Encabezado id_informeNavigation { get; set; }
}