// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Informes_Encabezado
{
    public int IdInforme { get; set; }
    public int IdUsuario { get; set; }
    public string Titulo { get; set; }
    public bool EstaEliminado { get; set; }
    public DateTime FechaCreacion { get; set; }
    public DateTime FechaModificacion { get; set; }

    public virtual ICollection<Detalle_Informe> Detalle_Informe { get; set; } = new List<Detalle_Informe>();
    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();
    public virtual Usuarios IdUsuarioNavigation { get; set; }
}