// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Informes_Encabezado
{
    public int IdInforme { get; set; }

    public int? IdMantenimiento { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<Detalle_Informe> Detalle_Informe { get; set; } = new List<Detalle_Informe>();

    public virtual Mantenimiento IdMantenimientoNavigation { get; set; }

    public virtual ICollection<Bitacora> Bitacoras { get; set; } = new List<Bitacora>();
}