// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Informes_Encabezado
{
    public int id_informe { get; set; }

    public int? id_cronogramas { get; set; }

    public DateTime? fecha { get; set; }

    public virtual ICollection<Detalle_Informe> Detalle_Informe { get; set; } = new List<Detalle_Informe>();

    public virtual Cronogramas id_cronogramasNavigation { get; set; }
}