// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Mantenimientos
{
    public int id_mantenimiento { get; set; }

    public string tipo_mantenimiento { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Cronogramas> Cronogramas { get; set; } = new List<Cronogramas>();
}