// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Parquadero
{
    public int id_parqueadero { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string estado { get; set; }

    public virtual ICollection<Cronogramas> Cronogramas { get; set; } = new List<Cronogramas>();
}