// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Parqueadero
{
    public int IdParqueadero { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Mantenimiento> Mantenimientos { get; set; } = new List<Mantenimiento>();
}