// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using UrbaPark.Dominio.Modelo.Entidades;

namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Roles
{
    public int id_rol { get; set; }

    public string nombre_rol { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}