// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using UrbaPark.Dominio.Modelo.Entidades;

namespace UrbaPark.Dominio.Modelo.Entidades;

public partial class Roles
{
    public int IdRol { get; set; }
    public string NombreRol { get; set; }
    public string Descripcion { get; set; }
    public bool EstaEliminado { get; set; }
    public DateTime FechaCreacion { get; set; }
    public DateTime FechaModificacion { get; set; }

    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}