// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int id_usuario { get; set; }

    public int? id_rol { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string correo { get; set; }

    public string estado { get; set; }

    public string cedula { get; set; }

    public virtual ICollection<Cronogramas> Cronogramas { get; set; } = new List<Cronogramas>();

    public virtual Roles id_rolNavigation { get; set; }
}