// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class Pisip_UrbanParkContext : DbContext
{
    public Pisip_UrbanParkContext()
    {
    }

    public Pisip_UrbanParkContext(DbContextOptions<Pisip_UrbanParkContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bitacora> Bitacora { get; set; }

    public virtual DbSet<Cronogramas> Cronogramas { get; set; }

    public virtual DbSet<Detalle_Informe> Detalle_Informe { get; set; }

    public virtual DbSet<Informes_Encabezado> Informes_Encabezado { get; set; }

    public virtual DbSet<Mantenimientos> Mantenimientos { get; set; }

    public virtual DbSet<Parquadero> Parquadero { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-M6S1CEH\\SQLEXPRESS;Initial Catalog=Pisip_UrbanPark;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bitacora>(entity =>
        {
            entity.HasKey(e => e.id_bitacora).HasName("PK__Bitacora__7E4268B0866136D2");

            entity.Property(e => e.descripcion)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.fecha_hora).HasColumnType("datetime");
            entity.Property(e => e.imagen_url)
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.HasOne(d => d.id_cronogramasNavigation).WithMany(p => p.Bitacora)
                .HasForeignKey(d => d.id_cronogramas)
                .HasConstraintName("FK__Bitacora__id_cro__44FF419A");
        });

        modelBuilder.Entity<Cronogramas>(entity =>
        {
            entity.HasKey(e => e.id_cronogramas).HasName("PK__Cronogra__BEB925820A59D82B");

            entity.Property(e => e.fecha_creacion).HasColumnType("datetime");
            entity.Property(e => e.fecha_fin).HasColumnType("datetime");
            entity.Property(e => e.fecha_inicio).HasColumnType("datetime");
            entity.Property(e => e.observaciones)
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.HasOne(d => d.id_mantenimientoNavigation).WithMany(p => p.Cronogramas)
                .HasForeignKey(d => d.id_mantenimiento)
                .HasConstraintName("FK__Cronogram__id_ma__4222D4EF");

            entity.HasOne(d => d.id_parqueaderoNavigation).WithMany(p => p.Cronogramas)
                .HasForeignKey(d => d.id_parqueadero)
                .HasConstraintName("FK__Cronogram__id_pa__412EB0B6");

            entity.HasOne(d => d.id_usuarioNavigation).WithMany(p => p.Cronogramas)
                .HasForeignKey(d => d.id_usuario)
                .HasConstraintName("FK__Cronogram__id_us__403A8C7D");
        });

        modelBuilder.Entity<Detalle_Informe>(entity =>
        {
            entity.HasKey(e => e.id_detInfo).HasName("PK__Detalle___888420765569AF1A");

            entity.Property(e => e.archivo_url)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.descripcion)
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.HasOne(d => d.id_informeNavigation).WithMany(p => p.Detalle_Informe)
                .HasForeignKey(d => d.id_informe)
                .HasConstraintName("FK__Detalle_I__id_in__4AB81AF0");
        });

        modelBuilder.Entity<Informes_Encabezado>(entity =>
        {
            entity.HasKey(e => e.id_informe).HasName("PK__Informes__ECCCE10F31757FB6");

            entity.Property(e => e.fecha).HasColumnType("datetime");

            entity.HasOne(d => d.id_cronogramasNavigation).WithMany(p => p.Informes_Encabezado)
                .HasForeignKey(d => d.id_cronogramas)
                .HasConstraintName("FK__Informes___id_cr__47DBAE45");
        });

        modelBuilder.Entity<Mantenimientos>(entity =>
        {
            entity.HasKey(e => e.id_mantenimiento).HasName("PK__Mantenim__707E5D16AF7ADCAF");

            entity.Property(e => e.descripcion)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.tipo_mantenimiento)
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Parquadero>(entity =>
        {
            entity.HasKey(e => e.id_parqueadero).HasName("PK__Parquade__0A2A3B21893B63E6");

            entity.Property(e => e.direccion)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.estado)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.id_rol).HasName("PK__Roles__6ABCB5E0745D9BAC");

            entity.Property(e => e.descripcion)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.nombre_rol)
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PK__Usuarios__4E3E04AD51CD0BF7");

            entity.Property(e => e.apellido)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.cedula)
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.correo)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.estado)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.HasOne(d => d.id_rolNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.id_rol)
                .HasConstraintName("FK__Usuarios__id_rol__398D8EEE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}